- app/views/records/edit_fields/_displays.html.erb
sorry I didn't do this one at the same time as tufts_models I forget that you have ti make it valid in the model, and also available in mira.
> adds nowhere as a displays destination

- Gemfile
- app/mailers/notifier.rb
- app/views/notifier/derivatives_failure.html.erb
- app/views/notifier/derivatives_failure.text.erb
- config/application.yml
- config/environments/development.rb
- config/environments/production.rb
- config/environments/tdldev.rb
- config/environments/test.rb
- lib/job/create_derivatives.rb
- spec/job/create_derivatives_spec.rb
@jcoyne this branch contains the mira changes corresponding to the recently-pulled tufts_model changes for PDF derivatives and is ready to be merged, please and thank you.
> Pdf derivatives

- .gitignore
- README.md
- config/database.yml.sample
- lib/tasks/config.rake
* update README
* add rake task to copy config files from samples
* make mysql2 the default database (and include instructions for installing mysql on osx)
> updated README/install instructions

- spec/job/revert_spec.rb
We need to ensure that record did not exist instead of asserting it
didn't exist.
> Fix a test that was broken intermittently

- Gemfile
- Gemfile.lock
- app/views/attachments/files_form/_tufts_video.html.erb
- app/views/catalog/_show_tufts_video.html.erb
- spec/factories/tufts_video.rb
- spec/job/create_derivatives_spec.rb
@tonyc @jcoyne This is the rest of the video derivatives code, I see in travis you guys have 1 failing test, this branch fails that same test.  I'm guessing you may want these tests excluded on travis because they require ffmpeg?
> Video derivatives

- Gemfile
- Gemfile.lock
- app/actions/xml_batch_import_action.rb
- app/controllers/batches/xml_import_controller.rb
- db/migrate/20150521145848_create_uploaded_files.rb
- db/schema.rb
- spec/controllers/batches/xml_import_controller_spec.rb
- spec/controllers/batches_controller_spec.rb
- spec/support/shared/batch_import_updates.rb
> Update to use the new UploadedFile model

- app/controllers/catalog_controller.rb
> On the show page 'pid' should only have one colin

- app/assets/javascripts/application.js
- app/assets/javascripts/attachments.js
- app/assets/stylesheets/tufts.css.scss
- app/controllers/attachments_controller.rb
- app/helpers/attachments_helper.rb
- app/views/attachments/files_form/_default.html.erb
- app/views/attachments/files_form/_tufts_audio.html.erb
- app/views/attachments/files_form/_tufts_pdf.html.erb
- app/views/attachments/files_form/_tufts_video.html.erb
- app/views/attachments/files_form/_upload.html.erb
- app/views/attachments/index.html.erb
- spec/controllers/attachments_controller_spec.rb
> Allow user to remove a previously attached transfer file from TuftsPDF

- README.md
- config/secrets.yml.sample
> adds resque-pool to README, fixes handle example

- config/deploy.rb
> shares tmp and uploads dirs for capistrano

- Gemfile
- Gemfile.lock
- app/controllers/records_controller.rb
- app/views/records/edit_fields/_displays.html.erb
- spec/controllers/records_controller_spec.rb
Fix error messages.
Fixes #476
> Remove blank and non-unique displays.

- app/helpers/batches_helper.rb
- app/views/batches/_batch_actions.html.erb
- spec/helpers/batches_helper_spec.rb
- spec/views/batches/_batch_actions.html.erb_spec.rb
because button_to doesn't accept nested params (like pids)
Fixes #495
> Add batch_action_button

- app/services/register_handle_service.rb
- lib/job/register_handle.rb
- spec/job/register_handle_spec.rb
> Handle job service takes an object not a string.

- app/views/batch/metadata_imports/new.html.erb
- app/views/batch/xml_imports/new.html.erb
- app/views/catalog/_admin_home.html.erb
> Update import wording for clarity

- app/services/register_handle_service.rb
- config/application.yml
- config/secrets.yml.sample
> Change handle config to use prefix and passphrase

- app/parsers/metadata_xml_parser.rb
- spec/parsers/metadata_xml_parser_spec.rb
> Require a pid on import with multiple datastreams

- config/resque-pool.yml.sample
Active config changed to this pattern on both devmira and mira.
> adds manifest queue, closes #582

- app/services/import_service.rb
- lib/job/import.rb
- lib/job/run_as_batch_item.rb
- spec/job/import_spec.rb
- spec/services/import_service_spec.rb
> Import metadata sets batchID on the objects

- app/assets/stylesheets/catalog.css.scss
- app/views/catalog/_document_list.html.erb
- app/views/catalog/_export_datastream_form.html.erb
- app/views/catalog/_show_tools.html.erb
- spec/features/export_datastreams_spec.rb
> clean up the styling and wording of the export datastreams buttons.

- app/presenters/xml_import_presenter.rb
- app/views/batch/xml_imports/_batch_info.html.erb
- app/views/batch/xml_imports/show.html.erb
- spec/presenters/xml_import_presenter_spec.rb
- spec/views/batch/xml_imports/show.html.erb_spec.rb
on the import archival content show page.
Fixes #525 (again)
> Display count of uploaded datastreams

- app/controllers/downloads_controller.rb
- app/services/archival_storage_service.rb
- spec/controllers/downloads_controller_spec.rb
- spec/services/archival_storage_service_spec.rb
> Preserve original filename of Transfer.binary

- Gemfile.lock
- db/schema.rb
> Make batches.metadata_file a LONGTEXT field

- app/controllers/catalog_controller.rb
> Change title sort to use fields that exist in the index

- app/controllers/batch/publishes_controller.rb
- app/controllers/batch/purges_controller.rb
- app/controllers/batch/reverts_controller.rb
- app/controllers/batch/unpublishes_controller.rb
- app/controllers/batches_controller.rb
- spec/controllers/batch/publishes_controller_spec.rb
- spec/controllers/batch/purges_controller_spec.rb
- spec/controllers/batch/reverts_controller_spec.rb
- spec/controllers/batch/unpublishes_controller_spec.rb
> Ensure pids submitted are unique for various batch actions.
